export const thesisEn = {
  title: 'Investment thesis', empty: 'Record why you follow this asset and what would change your view.', create: 'Create thesis', edit: 'Edit thesis', check: 'Check saved evidence', refresh: 'Reload', loading: 'Loading thesis…',
  details: 'Conditions and evidence', history: 'Versions and check history', thesis: 'Investment reasoning', horizon: 'Time horizon', changeNote: 'Reason for this version', enabled: 'Check after each scan', save: 'Save new version', cancel: 'Cancel', add: 'Add condition', remove: 'Remove condition', condition: 'Condition', kind: 'Role', support: 'Supporting condition', invalidate: 'Invalidation condition', metric: 'Observation', operator: 'Comparison', threshold: 'Threshold',
  note: 'Checks use the latest completed observation. They do not establish persistent trends or a probability that the thesis is true. Text conditions require manual review.',
  count: '{{supported}} supporting · {{triggered}} invalidation triggers · {{unknown}} unknown', checked: 'Last saved check {{time}}', version: 'Version {{version}} · {{time}}', noCheck: 'This version has not been checked yet.', checkError: 'The latest check could not be saved. Previous evidence is shown; retry the check.', limited: 'Showing up to 50 versions and 100 recent checks.', noHistory: 'No checks saved yet.', archived: 'Status at the original check time', source: 'Source', dataAt: 'Data as of', observedAt: 'Observed', value: 'Observed value', scope: 'This is a separate thesis check. It does not change trend judgments or Jev forecasts.', draftHint: 'Write your own reasoning. Do not enter credentials or private account details.', placeholder: 'What facts make this asset worth following?', horizonPlaceholder: 'For example, next three months', reasonPlaceholder: 'Why are you creating or changing these conditions?', example: 'Illustrative demo data',
  status: { paused: 'Checks paused', triggered: 'Invalidation condition triggered', incomplete: 'Evidence incomplete', supported: 'Configured supporting conditions met', watch: 'Continue watching' },
  result: { met: 'Met', 'not-met': 'Not met', unknown: 'Cannot assess' },
  reason: { available: 'Available', manual: 'Manual review required', missing: 'No usable observation', stale: 'Observation expired', 'source-unavailable': 'Source unavailable or retained reference only', 'formula-changed': 'Metric definition changed', 'invalid-time': 'Time cannot be verified' },
  error: { 'thesis-conflict': 'Another version was saved. Your draft is retained. Cancel editing, reload and compare before saving again.', 'thesis-invalid': 'Check the required fields, unique conditions and numeric thresholds.', 'thesis-unavailable': 'Thesis data could not be loaded or saved. Your draft is retained.' },
  metrics: { 'daily-close': 'Completed daily close (USD)', 'daily-change': 'Daily change (%)', 'volume-ratio': 'Volume / 20-day average', 'funding-8h': 'Deribit 8-hour funding (%)', 'annualized-basis': 'Deribit annualized basis (%)', 'put-call-ratio': 'Deribit put/call open-interest ratio', 'strategy-mnav': 'Official Strategy mNAV (net BPS)', manual: 'Text condition · manual review' },
  units: { usd: 'USD', percent: '%', ratio: '×', text: '' },
}
export const thesisZh: typeof thesisEn = {
  title: '投资逻辑跟踪', empty: '记录关注这个资产的理由，以及哪些变化会让你重新审视它。', create: '建立逻辑档案', edit: '编辑逻辑', check: '核验已采集证据', refresh: '重新载入', loading: '正在读取逻辑档案…',
  details: '查看条件与证据', history: '版本与核验历史', thesis: '投资逻辑', horizon: '观察期限', changeNote: '本次版本的修改原因', enabled: '每次扫描后自动核验', save: '保存新版本', cancel: '取消', add: '增加条件', remove: '移除条件', condition: '条件描述', kind: '条件作用', support: '支持条件', invalidate: '失效条件', metric: '观察指标', operator: '比较方式', threshold: '阈值',
  note: '数值条件检查最近一个已完成的观察值，不代表连续趋势，也不是逻辑成立的概率。文字条件需人工核验。',
  count: '{{supported}} 项支持 · {{triggered}} 项失效触发 · {{unknown}} 项无法判断', checked: '最近保存的核验 {{time}}', version: '第 {{version}} 版 · {{time}}', noCheck: '此版本尚无核验记录。', checkError: '最近核验未能保存，目前展示先前证据，请重试核验。', limited: '最多展示最近 50 个版本、100 次核验。', noHistory: '尚无核验记录。', archived: '以下为当时核验结果', source: '来源', dataAt: '数据时间', observedAt: '采集时间', value: '观察值', scope: '投资逻辑跟踪独立展示，不修改趋势判断或 Jev 预测。', draftHint: '请填写自己的判断理由，不要填写密钥或私人账户信息。', placeholder: '哪些事实让这个资产值得关注？', horizonPlaceholder: '例如：未来三个月', reasonPlaceholder: '为什么建立或调整这些条件？', example: '以下为演示数据',
  status: { paused: '已暂停自动核验', triggered: '有失效条件触发', incomplete: '证据尚不完整', supported: '已设定的支持条件满足', watch: '继续观察' },
  result: { met: '满足', 'not-met': '未满足', unknown: '无法判断' },
  reason: { available: '可用', manual: '需人工核验', missing: '暂无有效观察值', stale: '数据已过期', 'source-unavailable': '来源不可用，或仅有缓存参考值', 'formula-changed': '指标口径已改变', 'invalid-time': '数据时间无法核实' },
  error: { 'thesis-conflict': '已有新版本保存，当前草稿已保留。请取消编辑、重新载入并对比后再保存。', 'thesis-invalid': '请检查必填内容、重复条件和数值阈值。', 'thesis-unavailable': '逻辑档案读取或保存失败，编辑中的草稿已保留。' },
  metrics: { 'daily-close': '已收盘日线价格（USD）', 'daily-change': '日线涨跌幅（%）', 'volume-ratio': '成交量／20 日均量', 'funding-8h': 'Deribit 八小时资金费率（%）', 'annualized-basis': 'Deribit 年化基差（%）', 'put-call-ratio': 'Deribit 看跌／看涨持仓比', 'strategy-mnav': 'Strategy 官方 mNAV（净每股含币口径）', manual: '文字条件 · 人工核验' },
  units: { usd: 'USD', percent: '%', ratio: '倍', text: '' },
}
